### ISSUE TITLE
Fatal error System.TypeInitializationException.

### ISSUE THREAD

**Issue by PineAppleGrits** [FragLand/terracord#107]
### Expected Behavior
* 
Not loading
### Actual Behavior/Symptoms
*  Terraria server isn't loading

### How to Reproduce Behavior/Symptoms
* 

### Terracord Version
*
1.2.0
### Terraria/TShock Version
*
TShock 1.4.0.5
### Discord.Net Version
*

### .NET/Mono Version
* 

### Operating System
*
Ubuntu 16.04
### Output/Screenshot(s)

![image](https://user-images.githubusercontent.com/66481194/95361567-48436580-08a3-11eb-840d-76889edd3741.png)

**Comment by PineAppleGrits** [comment]
![image](https://user-images.githubusercontent.com/66481194/95365187-33b59c00-08a8-11eb-891b-fb3e78872c4b.png)

**Comment by ldilley** [comment]
Apologies for the delay, @PineAppleGrits.

This is an issue related to Discord.Net, which is a dependency of Terracord, and not an issue with Terracord itself. Discord.Net does not support Mono according to this GitHub issue: https://github.com/discord-net/Discord.Net/issues/910 and the Discord.Net documentation here: https://discord.foxbot.me/docs/guides/getting_started/installing.html?tabs=vs-install%2Ccore2-1.

The relevant excerpts are:
```
Mono is not a supported runtime. Switch to .NET Core.
```

```
Warning

Using this library with Mono is not supported until further notice. It is known to have issues with the library's WebSockets implementation and may crash the application upon startup.
```

Lack of Mono support is also noted in Terracord's README.md: https://github.com/FragLand/terracord/blob/master/.github/README.md

```
⚠️ Unfortunately, Terracord may not work with Mono. This is due to Discord.Net not supporting Mono.
```

You can try another runtime such as .NET Core or .NET 5 on Linux instead of Mono.

**Comment by ldilley** [comment]
@Dids also reported in issue #95 that Terracord does work under Linux using Mono 6.8 if you use the net46 target and not the netstandard2.0 target (which is the DLL included in the latest release zip archive). So, you'll have to build the net46 DLL and possibly update Mono. Have a look at his Dockerfile for details: https://github.com/Didstopia/terraria-server/blob/master/Dockerfile. I hope this information helps.

**Comment by PineAppleGrits** [comment]
Hey thank you, i didnt try it yet but i will! Continue making awesome things!
