### ISSUE TITLE
Add administrative TShock commands

### ISSUE THREAD

**Issue by ldilley** [FragLand/terracord#24]
### Feature Description
* Allow the bot owner and perhaps a configurable Discord role remote access to administrative TShock commands such as `ban`, `kick`, `kill`, `mute`, `reload`, `restart`, `save`, `stop`, `tp`, etc.

**Comment by moisterrific** [comment]
Not sure how this would work on the Discord side of things. But all those commands (besides TP) can be assigned a new group in TShock with permissions on par with super admin or even just make it connect to super admin itself.

Since Discord relaying commands in game wont be a real player. I’m guessing it will have about the same functions as the console, which means some commands that can only be used in-game won’t work with the relay.

**Comment by ldilley** [comment]
I will likely move this feature to release `1.2.0` since it may involve a significant amount of work to implement an unknown number of TShock commands.
