### ISSUE TITLE
In-game @ relay breaks if server has users with || in name

### ISSUE THREAD

**Issue by moisterrific** [FragLand/terracord#46]
### Expected Behavior
* mention users from in-game "just works"

### Actual Behavior/Symptoms
* could not mention ANY users if the server contains users that have `||` in their username, and if you just do a `@` without any name, it will end up mentioning that user with the || a bunch of times. However, after I kicked those two users from my server it works as intended. 

### How to Reproduce Behavior/Symptoms
* try mentioning anyone if your server contains users with || in their username, not nickname

### Terracord Version
* 1.0.0

### Terraria/TShock Version
* 4.3.26 mobile (though it shouldn't make much of a diff since the code is pretty much identical)

### Discord.Net Version
* dunno 

### .NET/Mono Version
* dunno

### Operating System
* Windows 10

### Output/Screenshot(s)
![image](https://user-images.githubusercontent.com/57187883/72634662-00ea0300-3929-11ea-8d01-50985a426e61.png)

![image](https://user-images.githubusercontent.com/57187883/72634711-13643c80-3929-11ea-8e8d-b8b3e2e742b1.png)
[terracord.log](https://github.com/FragLand/terracord/files/4078100/terracord.log)

**Comment by ldilley** [comment]
Hehe; I like the Cortana bot. ;)

Per our earlier Discord discussion, `@` by itself triggering multiple mentions is a blatant bug. This is due to the following faulty regex patterns:

```cs
string channelPattern = "[#](.*)";
string roleUserPattern = "[@](.*)";
```

`.*` means **zero** or more matches. `@` or `#` by themselves are not valid channels, roles, or users. These patterns need to be updated to read:

```cs
string channelPattern = "[#](.+)";
string roleUserPattern = "[@](.+)";
```

This will match one or more characters beyond the `@` and `#` characters. I will commit a fix later this evening. I am hoping that it also resolves the issue with the `|` character in usernames.

**Comment by ldilley** [comment]
Is this issue resolved with the latest commit (at the time of this reply), 23d806a?

**Comment by moisterrific** [comment]
Yup it's fixed in that commit.
