### ISSUE TITLE
Make it so bot commands don't get relayed to game chat

### ISSUE THREAD

**Issue by moisterrific** [FragLand/terracord#47]
### Feature Description
* what the title says lol

**Comment by ldilley** [comment]
We could prevent Terracord bot commands issued by other users from being transmitted by checking for the configurable command prefix. Discord bot responses are already not relayed. A couple of other thoughts:

1. This behavior may not be desirable. Personally, I like being able to see who issues what commands from within the game.
2. If you are thinking about including other bots within a Discord server, this will be more difficult to implement since they may be using other prefixes and we'd also need to blacklist by role perhaps.

Any additional thoughts given the above?

**Comment by ldilley** [comment]
Would you be satisfied with a configurable toggle that ignores messages from Discord users when the message start contains the Terracord bot's command prefix?

**Comment by moisterrific** [comment]
That would be nice, yeah
