### ISSUE TITLE
Netstandart Error

### ISSUE THREAD

**Issue by EMREOYUN** [FragLand/terracord#68]
### Expected Behavior
* Plugin Works.

### Actual Behavior/Symptoms
* Netstandart not found.

### How to Reproduce Behavior/Symptoms
* Just start the server with plugins.

### Terracord Version
* 1.1.0

### Terraria/TShock Version
* 1.3.0.7 / 2.1 (PE)[TShock Zombie]

### Discord.Net Version
* Check from Terracord Release 1.1.0

### .NET/Mono Version
* -

### Operating System
* Windows Server 2012 R2

### Output/Screenshot(s)
* None

### Additional Notes
* There is no space that .NET SDK can be installable on our Server(Drains too much RAM and Disk that not allows our servers run).

**Comment by ldilley** [comment]
Greetings, @EMREOYUN.

How are you running TShock? It should require a .NET interpreter. The same interpreter should be able to load Terracord just fine. Also, I doubt that Terracord would be supported on your version of Terraria (1.3.0.7)/TShock (4.3.8) considering it is almost half a decade old. The API version for TShock 4.3.8 is 1.21. Terracord uses API version 2.1. You would need to upgrade to at least version 4.3.24 of TShock (latest version at the time of this reply is 4.3.26) to use Terracord.

In regards to the .NET SDK, you only require this software if you are building Terracord from source. The supplied DLL contained in the release zip archives only requires the .NET runtime which consumes less disk space than the SDK. As mentioned previously, you should already have some version of the .NET runtime installed on your server in order to run TShock.

**Comment by EMREOYUN** [comment]
> Greetings, @EMREOYUN.
> 
> How are you running TShock? It should require a .NET interpreter. The same interpreter should be able to load Terracord just fine. Also, I doubt that Terracord would be supported on your version of Terraria (1.3.0.7)/TShock (4.3.8) considering it is almost half a decade old. The API version for TShock 4.3.8 is 1.21. Terracord uses API version 2.1. You would need to upgrade to at least version 4.3.24 of TShock (latest version at the time of this reply is 4.3.26) to use Terracord.
> 
> In regards to the .NET SDK, you only require this software if you are building Terracord from source. The supplied DLL contained in the release zip archives only requires the .NET runtime which consumes less disk space than the SDK. As mentioned previously, you should already have some version of the .NET runtime installed on your server in order to run TShock.

Mobile Clients hates 4.3.26. We are using 1.3.0.7 with API 2.1(It's modificated version). .NET Framework already installed but netstandart is not part of .NET Framework i think, it is part of .NET SDK.

This is our modified code: https://github.com/chi-rei-den/TShock/

**Comment by ldilley** [comment]
Ah. I am not familiar with the mobile version at all. Fortunately, @moisterrific is... Was there anything special you had to do, @moisterrific, to get Terracord working with your mobile server?

Terracord targets .NET Standard 2.0 and should work with .NET Framework >=4.6.1, .NET Core runtime 2.0, and possibly Mono 5.4 according to this .NET implementation support table: https://docs.microsoft.com/en-us/dotnet/standard/net-standard

**Comment by moisterrific** [comment]
Nothing special, just very basic reference change and changing a few lines of code copy/pasted from the mobile source lol

the setup procedure is otherwise identical to how you’d do it for PC

**Comment by ldilley** [comment]
@EMREOYUN: What .NET interpreter, including version, are you using? The issue template you used did not seem to have a proper response in the `.NET/Mono Version` section. Can you also please include any relevant error messages from the console output when trying to start the server and plugin?

**Comment by EMREOYUN** [comment]
> @EMREOYUN: What .NET interpreter, including version, are you using? The issue template you used did not seem to have a proper response in the `.NET/Mono Version` section. Can you also please include any relevant error messages from the console output when trying to start the server and plugin?

.NET: 4.0
Mono: 6.8.0.105

**Comment by ldilley** [comment]
Discord.Net (a dependency of Terracord) is unsupported under Mono. .NET Framework 4.0 is also rather old and does not support .NET Standard 2.0. You need at least .NET Framework 4.6.1 to support .NET Standard 2.0 which is what `Terracord.dll` targets. The problem here is clearly with your interpreter. You need to upgrade to or install either .NET Framework >=4.6.1 or .NET Core >=2.0 to use Terracord.

Since you have the path forward, I'll close this issue in at least 72 hours from now. Please let us know if you have any further questions.

**Comment by EMREOYUN** [comment]
> Discord.Net (a dependency of Terracord) is unsupported under Mono. .NET Framework 4.0 is also rather old and does not support .NET Standard 2.0. You need at least .NET Framework 4.6.1 to support .NET Standard 2.0 which is what `Terracord.dll` targets. The problem here is clearly with your interpreter. You need to upgrade to or install either .NET Framework >=4.6.1 or .NET Core >=2.0 to use Terracord.
> 
> Since you have the path forward, I'll close this issue in at least 72 hours from now. Please let us know if you have any further questions.

Weird, how i can find .Net 4.6.1? Offical website downloads 4.0 version.

**Comment by kyleighd** [comment]
Your version was end of life on 2016-01-12. I'm not sure where you are seeing that only 4.0 is available.
Here are the official Microsoft download links.
https://dotnet.microsoft.com/download
https://dotnet.microsoft.com/download/dotnet-framework

**Comment by EMREOYUN** [comment]
Issue fixed and Terracord works well for now.

**Comment by EMREOYUN** [comment]
Closed #68
